@startuml
'https://plantuml.com/object-diagram

object SellerGroup
object User
object FixedPriceListing
object Product

SellerGroup "0,1"--> "0..*" User

FixedPriceListing "0..*" --> "1" Product

@enduml
